ajaxblog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls'))    
]

myapp/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.show_data,name='home'),
    # path('update/',views.update_data,name='update'),
    path('save/',views.Save_form,name='save'), 
    path('delete/',views.delete_data,name='delete'),
    path('edit/',views.edit_data, name='edit'),   
  
]

myapp/models.py
from django.db import models

# Create your models here.
class blog(models.Model):
    title=models.CharField(max_length=150)
    dis=models.TextField()

myapp/forms.py
from django import forms
from .models import blog
class Postform(forms.ModelForm):
  class Meta:
   model = blog
   fields = ['title','dis']

myapp/views.py
from django.shortcuts import render,HttpResponseRedirect
from django.http import JsonResponse
from.models import blog
from .forms import Postform
# Create your views here.
def show_data(request):
    data=blog.objects.all()
    fm=Postform()   
    return render(request,'myapp/home.html',{'form':fm,'data':data})

def Save_form(request):
    if request.method == 'POST':
        fm = Postform(request.POST)
        if fm.is_valid():
            sid = request.POST.get('stuid')
            title = request.POST['title']
            dis = request.POST['dis']
            if (sid == ''):
                usr = blog(id=sid,title=title, dis=dis)
            else:  
                usr = blog(id=sid, title=title, dis=dis)
                usr.save()
                stud = blog.objects.values()
                student_data = list(stud)
                return JsonResponse({'status': 'Save', 'student_data': student_data})
        else:
            return JsonResponse({'status': 0})
    else:
        return JsonResponse({'status': 0})





###delete
def delete_data(request):
    if request.method =="POST":
        id = request.POST.get('sid')
        print(id)
        pi = blog.objects.get(pk=id)
        pi.delete()
        return JsonResponse({'status': 1})
    else:
        return JsonResponse({'status': 0})

#Edit Data
def edit_data(request):
    if request.method == "POST":
        id = request.POST.get('sid')
        print(id)
        student = blog.objects.get(pk=id)
        student_data = {"id":student.id,"title":student.title,"dis":student.dis}
        return JsonResponse(student_data)          


# def delete_data(request,id):
#    if request.method=='POST':
#       d=blog.objects.get(pk=id)
#       d.delete()
#       return JsonResponse({'status':1})
#    else:
#       return JsonResponse({'status':0})

myapp/templates/myapp/ajax.html
<script>
    $("#btnsave").click(function (){
        console.log("Save button clicked");
        output = "";
        let sid = $("#stuid").val();
        let title = $("#id_title").val(); 
        let dis= $("#id_dis").val();
        
        let csr =$("input[name=csrfmiddlewaretoken]").val();
        
        if (title === "") {
            console.log("Please enter title");
        } else if (dis === "") {
            console.log("Enter your description");
        } else {
            console.log(title);
            console.log(dis);
            mydata = {title: title, dis: dis, stuid: sid ,csrfmiddlewaretoken: csr };
            $.ajax({
                url: "{% url 'save' %}",
                method: "POST",
                data: mydata,
                success: function(data) {
                    x = data.student_data;
                    if (data.status === "Save") {
                        console.log("Form submitted successfully");
                        console.log(x);
                        for (i = 0; i < x.length; i++) {
                            output += "<tr><td>" + x[i].id + "</td><td>" + x[i].title + "</td><td>"  + x[i].dis +   "</td><td> <input type='button' class='btn btn-warning btn-sm btn-edit' value='edit' data-sid=" + x[i].id +
                            "><input type='button' class='btn btn-danger btn-sm btn-del' value='Delete' data-sid=" + x[i].id + ">";
                            
                        }
                        $("#tbody").html(output);
                        $("#stuid").val('');
                        $("form")[0].reset();
                     }
                     if (data.status === 0) {
                        console.log("Unable to Save Form");
                        $("#stuid").val('');
                        $("form")[0].reset();                        
                    }
                }
            });
        }
    });

// Delete data
$("tbody").on("click", ".btn-del", function (){
    console.log("Delete button clicked");
    let id = $(this).data("sid"); // Change from attr("data-sid") to data("sid")
    let csr = $("input[name=csrfmiddlewaretoken]").val();

    mydata = { sid: id, csrfmiddlewaretoken: csr };
    mythis = this;
    $.ajax({
        url: "{% url 'delete' %}",
        method: "POST",
        data: mydata,
        success: function (data) {
            // console.log(data); 
            if(data.status == 1){
                console.log("data deleted successfuly ")
                $(mythis).closest("tr").fadeOut();
            }
            if(data.status == 0){
                console.log("data not delete successfuly ")
            }            
        },
    });
});

//EDIT DATA
$("tbody").on("click", ".btn-edit", function (){
    console.log("Delete button clicked");
    let id = $(this).data("sid"); // Change from attr("data-sid") to data("sid")
    let csr = $("input[name=csrfmiddlewaretoken]").val();

    mydata = { sid: id, csrfmiddlewaretoken: csr };
    $.ajax({
        url: "{% url 'edit' %}",
        method: "POST",
        data: mydata,
        success: function (data) {
             console.log(data);
           $("#stuid").val(data.id)
           $("#id_title").val(data.title)
           $("#id_dis").val(data.dis)            
        },
    });
});


</script>

myapp/templates/myapp/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'myapp/css/bootstrap.css' %}">
    <title>blog</title>
</head>
<body>
 
    <h1 class="text-center alter alert-danger">CRUD Blog with Ajax </h1>


    <form action="" method="Post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="button" id="btnsave" value="Save">

        <input type="hidden" name="stuid" id="stuid"/>

    </form><br>


    <h1>here show data form database</h1>
    <!-- show data under code -->
    <table  >
        <thead >
          <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Description</th>
            <th>Update</th>
            <th>Delete</th>

          </tr>
        </thead>
        <tbody id="tbody">
          {% for x in data %}
          <tr>
            <td>{{ x.id }}</td>
            <td>{{ x.title }}</td>
            <td>{{ x.dis }}</td>
<!-- Updated data-sid attributes -->
          <td><input type="button" class="btn btn-warning btn-sm btn-edit" value="edit" data-sid="{{ x.id }}"></td>

          <td><input type="button" class="btn btn-danger btn-sm btn-del" value="Delete" data-sid="{{ x.id }}"></td>

          </tr>
          {% endfor %}
        </tbody>
      </table>
   <script src="{% static 'myapp/js/jquery.js' %}"></script>  
   <script src="{% static 'myapp/js/popper.js' %}"></script>   
   <script src="{% static 'myapp/js/bootstrap.js' %}"></script>  
   {% include "myapp/ajax.html" %} 
</body>
</html>

myapp/templates/myapp/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Data</title>
</head>
<body>
    <h1>update form</h1>
<!-- Modal for updating data -->
<div id="editModal" class="modal">
    <form id="editForm">
        {% csrf_token %}
        <!-- Form fields for updating data -->
        <input type="text" name="title" placeholder="Title">
        <textarea name="dis" placeholder="Description"></textarea>
        <button type="submit">Update</button>
    </form>
</div>
</body>
</html>